"""Initial Migrations

Revision ID: 7d66122c1a24
Revises: 
Create Date: 2022-02-12 08:40:55.692197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d66122c1a24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newslater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('useremail', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newslater')
    # ### end Alembic commands ###
